/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarView: typeof import('./src/components/CalendarView.vue')['default']
    EventCard: typeof import('./src/components/EventCard.vue')['default']
    EventDetailCard: typeof import('./src/components/EventDetailCard.vue')['default']
    FilterBar: typeof import('./src/components/FilterBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
